dist: bionic

language: python
cache:
  pip: true
  directories:
    - .tox

services:
  - mysql
  - postgresql

python:
  - '2.7'
  - '3.6'
  - '3.7'
  - '3.8'

env:
  - SQLALCHEMY_DATABASE_URI=
  - SQLALCHEMY_DATABASE_URI=postgresql://postgres@localhost/olapy_test
  - SQLALCHEMY_DATABASE_URI=mysql://travis@localhost/olapy_test

matrix:
  include:
    - python: 3.6
      env: TOXENV=lint

install:
  - pip install -U pip setuptools tox tox-travis wheel poetry

before_script:
  - psql -c 'create database olapy_test;' -U postgres
  - mysql -e 'create database olapy_test;'

script:
  - tox

notifications:
  slack:
    rooms:
      - abilian:dTtRD7DHS4Dw3jfRrqytQWU6#code
    on_success: change
    on_failure: always
